//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fohlio.RevitReportsIntegration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fohlio.RevitReportsIntegration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Account {
            get {
                object obj = ResourceManager.GetObject("Account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        public static string AccountPrompt {
            get {
                return ResourceManager.GetString("AccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing report borders.
        /// </summary>
        public static string BordersGenerationOperationName {
            get {
                return ResourceManager.GetString("BordersGenerationOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling... Wait....
        /// </summary>
        public static string CancellationWaitingPrompt {
            get {
                return ResourceManager.GetString("CancellationWaitingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        public static string CancelOperationPrompt {
            get {
                return ResourceManager.GetString("CancelOperationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing report cell values.
        /// </summary>
        public static string CellValuesGenerationOperationName {
            get {
                return ResourceManager.GetString("CellValuesGenerationOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F O H L I O.
        /// </summary>
        public static string CompanyLogoPrompt {
            get {
                return ResourceManager.GetString("CompanyLogoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue &gt;.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fohlio Parameter.
        /// </summary>
        public static string div_FohlioParameter {
            get {
                return ResourceManager.GetString("div_FohlioParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revit Parameter.
        /// </summary>
        public static string div_RevitParameter {
            get {
                return ResourceManager.GetString("div_RevitParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fohlio reports.
        /// </summary>
        public static string DockablePaneTitle {
            get {
                return ResourceManager.GetString("DockablePaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fohlio report.
        /// </summary>
        public static string DraftingReportViewFamilyTypeName {
            get {
                return ResourceManager.GetString("DraftingReportViewFamilyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sheets (duplicate reports).
        /// </summary>
        public static string DuplicateImportedReportsButtonTitle {
            get {
                return ResourceManager.GetString("DuplicateImportedReportsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Empty&gt;.
        /// </summary>
        public static string EmptyTitleBlockName {
            get {
                return ResourceManager.GetString("EmptyTitleBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fohlio_16 {
            get {
                object obj = ResourceManager.GetObject("Fohlio_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fohlio_32 {
            get {
                object obj = ResourceManager.GetObject("Fohlio_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FohlioLogo {
            get {
                object obj = ResourceManager.GetObject("FohlioLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string GoBackPrompt {
            get {
                return ResourceManager.GetString("GoBackPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of reports had been already imported.
        /// </summary>
        public static string ImportedReportsDuplicationsDialogTitle {
            get {
                return ResourceManager.GetString("ImportedReportsDuplicationsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing reports.
        /// </summary>
        public static string ImportReports {
            get {
                return ResourceManager.GetString("ImportReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string ImportReportsCommandTitle {
            get {
                return ResourceManager.GetString("ImportReportsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fohlio report.
        /// </summary>
        public static string ImportReportTransactionName {
            get {
                return ResourceManager.GetString("ImportReportTransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string LoginActionPrompt {
            get {
                return ResourceManager.GetString("LoginActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        public static string PagePrompt {
            get {
                return ResourceManager.GetString("PagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing report pictures.
        /// </summary>
        public static string PicturesGenerationOperationName {
            get {
                return ResourceManager.GetString("PicturesGenerationOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project.
        /// </summary>
        public static string ProjectListActionPrompt {
            get {
                return ResourceManager.GetString("ProjectListActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string projects_RecentProjects {
            get {
                return ResourceManager.GetString("projects_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshPrompt {
            get {
                return ResourceManager.GetString("RefreshPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command allows to create Revit view sheets with reports from fohlio.com.
        /// </summary>
        public static string ReportIntegrationCommandDescription {
            get {
                return ResourceManager.GetString("ReportIntegrationCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import
        ///reports.
        /// </summary>
        public static string ReportIntegrationCommandTitle {
            get {
                return ResourceManager.GetString("ReportIntegrationCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Fohlio reports into your Revit sheets.
        /// </summary>
        public static string ReportsListActionPrompt {
            get {
                return ResourceManager.GetString("ReportsListActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsPrompt {
            get {
                return ResourceManager.GetString("ReportsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string ResolutionPrompt {
            get {
                return ResourceManager.GetString("ResolutionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fohlio tools.
        /// </summary>
        public static string RibbonPanelTitle {
            get {
                return ResourceManager.GetString("RibbonPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutPrompt {
            get {
                return ResourceManager.GetString("SignOutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d474bfcb-0190-40bc-8dbe-5d0e78e3af29.
        /// </summary>
        public static string StorageEntitySchemaId {
            get {
                return ResourceManager.GetString("StorageEntitySchemaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a task.
        /// </summary>
        public static string task_ChooseTask {
            get {
                return ResourceManager.GetString("task_ChooseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull product quantity, floors, room codes and room names from Revit.
        /// </summary>
        public static string task_ExportDescription {
            get {
                return ResourceManager.GetString("task_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Fohlio.
        /// </summary>
        public static string task_ExportToFohlio {
            get {
                return ResourceManager.GetString("task_ExportToFohlio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert report.
        /// </summary>
        public static string task_InsertReport {
            get {
                return ResourceManager.GetString("task_InsertReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate schedules using Fohlio.com and insert by one-click.
        /// </summary>
        public static string task_ReportDescription {
            get {
                return ResourceManager.GetString("task_ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title block.
        /// </summary>
        public static string TitleBlockPrompt {
            get {
                return ResourceManager.GetString("TitleBlockPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update already imported reports.
        /// </summary>
        public static string UpdateImportedReportsButtonTitle {
            get {
                return ResourceManager.GetString("UpdateImportedReportsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserNamePrompt {
            get {
                return ResourceManager.GetString("UserNamePrompt", resourceCulture);
            }
        }
    }
}
